local H = _G.H
local Region = require("swap.region")

local function region(lines, ranges)
  local bufnr = H.buf(lines)
  return Region.from_ranges(bufnr, ranges), bufnr
end

H.group("region", function()
  H.test("splits a line into cells and gaps", function()
    local r = region({ "foo(aaa, b, cc)" }, { { 0, 4, 0, 7 }, { 0, 9, 0, 10 }, { 0, 12, 0, 14 } })
    H.eq({ r.cells[1].text, r.cells[2].text, r.cells[3].text }, { "aaa", "b", "cc" })
    H.eq(r.gaps, { ", ", ", " })
    H.eq(r:render(), "aaa, b, cc")
  end)

  H.test("swapping keeps the gaps in place", function()
    local r, bufnr = region({ "foo(aaa, b, cc)" }, { { 0, 4, 0, 7 }, { 0, 9, 0, 10 }, { 0, 12, 0, 14 } })
    r:swap(1, 3)
    r:apply()
    H.eq(H.lines(bufnr), { "foo(cc, b, aaa)" })
  end)

  H.test("a line break in a gap stays where it was", function()
    local r, bufnr = region({ "f(", "  aaa,", "  b", ")" }, { { 1, 2, 1, 5 }, { 2, 2, 2, 3 } })
    H.eq(r.gaps, { ",\n  " })
    r:swap(1, 2)
    r:apply()
    H.eq(H.lines(bufnr), { "f(", "  b,", "  aaa", ")" })
  end)

  H.test("grouping moves two items as one", function()
    local r, bufnr = region({ "(a, b, c)" }, { { 0, 1, 0, 2 }, { 0, 4, 0, 5 }, { 0, 7, 0, 8 } })
    H.ok(r:group(1))
    H.eq(r:count(), 2)
    H.eq(r.cells[1].text, "a, b")
    r:swap(1, 2)
    r:apply()
    H.eq(H.lines(bufnr), { "(c, a, b)" })
  end)

  H.test("ungrouping restores the items", function()
    local r = region({ "(a, b, c)" }, { { 0, 1, 0, 2 }, { 0, 4, 0, 5 }, { 0, 7, 0, 8 } })
    r:group(1)
    H.ok(r:ungroup(1))
    H.eq(r:count(), 3)
    H.eq(r:render(), "a, b, c")
  end)

  H.test("sorts and reverses", function()
    local r = region({ "(b, c, a)" }, { { 0, 1, 0, 2 }, { 0, 4, 0, 5 }, { 0, 7, 0, 8 } })
    r:sort(function(a, b)
      return a < b
    end)
    H.eq(r:render(), "a, b, c")
    r:reverse()
    H.eq(r:render(), "c, b, a")
  end)

  H.test("reports the item under a position", function()
    local r = region({ "foo(aaa, b, cc)" }, { { 0, 4, 0, 7 }, { 0, 9, 0, 10 }, { 0, 12, 0, 14 } })
    H.eq(r:index_at(0, 5), 1)
    H.eq(r:index_at(0, 9), 2)
    H.eq(r:index_at(0, 13), 3)
  end)

  H.test("ranges follow the items after a swap", function()
    local r = region({ "foo(aaa, b, cc)" }, { { 0, 4, 0, 7 }, { 0, 9, 0, 10 }, { 0, 12, 0, 14 } })
    r:swap(1, 2)
    H.eq(r:ranges()[1], { 0, 4, 0, 5 })
    H.eq(r:ranges()[2], { 0, 7, 0, 10 })
  end)

  H.test("undo snapshots round-trip", function()
    local r = region({ "(a, b, c)" }, { { 0, 1, 0, 2 }, { 0, 4, 0, 5 }, { 0, 7, 0, 8 } })
    local snap = r:snapshot()
    r:group(1)
    r:swap(1, 2)
    r:restore(snap)
    H.eq(r:render(), "a, b, c")
    H.eq(r:count(), 3)
  end)
end)
